"use strict";

// Generated by python scripts/branch_config.py. Do not edit manually.
globalThis.SCP_TAG_TRANSLATION_BRANCHES = Object.freeze(
  [
    {
      "branch": "cn",
      "site": "scp-wiki-cn",
      "label": "中文",
      "jp_branch_tag": "cn"
    },
    {
      "branch": "cs",
      "site": "scp-cs",
      "label": "Čeština",
      "jp_branch_tag": "cs"
    },
    {
      "branch": "de",
      "site": "scp-wiki-de",
      "label": "Deutsch",
      "jp_branch_tag": "de"
    },
    {
      "branch": "en",
      "site": "scp-wiki",
      "label": "English",
      "jp_branch_tag": "en"
    },
    {
      "branch": "es",
      "site": "lafundacionscp",
      "label": "Español",
      "jp_branch_tag": "es"
    },
    {
      "branch": "fr",
      "site": "fondationscp",
      "label": "Français",
      "jp_branch_tag": "fr"
    },
    {
      "branch": "int",
      "site": "scp-int",
      "label": "International",
      "jp_branch_tag": "int"
    },
    {
      "branch": "it",
      "site": "fondazionescp",
      "label": "Italiano",
      "jp_branch_tag": "it"
    },
    {
      "branch": "ko",
      "site": "scpko",
      "label": "한국어",
      "jp_branch_tag": "ko"
    },
    {
      "branch": "pl",
      "site": "scp-pl",
      "label": "Polski",
      "jp_branch_tag": "pl"
    },
    {
      "branch": "pt-br",
      "site": "scp-pt-br",
      "label": "Português",
      "jp_branch_tag": "pt"
    },
    {
      "branch": "th",
      "site": "scp-th",
      "label": "ภาษาไทย",
      "jp_branch_tag": "th"
    },
    {
      "branch": "ua",
      "site": "scp-ukrainian",
      "label": "Українська",
      "jp_branch_tag": "ua"
    },
    {
      "branch": "vn",
      "site": "scp-vn",
      "label": "Tiếng Việt",
      "jp_branch_tag": "vn"
    },
    {
      "branch": "zh-tr",
      "site": "scp-zh-tr",
      "label": "繁體中文",
      "jp_branch_tag": "zh"
    }
  ].map(Object.freeze),
);
