"""Supported SCP Wikidot sites and their local corpus branch codes."""

from __future__ import annotations

from dataclasses import dataclass
import json
from textwrap import indent


@dataclass(frozen=True)
class BranchConfig:
    branch: str
    site: str
    label: str
    jp_branch_tag: str


SUPPORTED_BRANCH_CONFIGS = (
    BranchConfig("cn", "scp-wiki-cn", "中文", "cn"),
    BranchConfig("cs", "scp-cs", "Čeština", "cs"),
    BranchConfig("de", "scp-wiki-de", "Deutsch", "de"),
    BranchConfig("en", "scp-wiki", "English", "en"),
    BranchConfig("es", "lafundacionscp", "Español", "es"),
    BranchConfig("fr", "fondationscp", "Français", "fr"),
    BranchConfig("int", "scp-int", "International", "int"),
    BranchConfig("it", "fondazionescp", "Italiano", "it"),
    BranchConfig("ko", "scpko", "한국어", "ko"),
    BranchConfig("pl", "scp-pl", "Polski", "pl"),
    BranchConfig("pt-br", "scp-pt-br", "Português", "pt"),
    BranchConfig("th", "scp-th", "ภาษาไทย", "th"),
    BranchConfig("ua", "scp-ukrainian", "Українська", "ua"),
    BranchConfig("vn", "scp-vn", "Tiếng Việt", "vn"),
    BranchConfig("zh-tr", "scp-zh-tr", "繁體中文", "zh"),
)


SUPPORTED_BRANCHES = tuple(config.branch for config in SUPPORTED_BRANCH_CONFIGS)
BRANCH_CONFIG_BY_CODE = {config.branch: config for config in SUPPORTED_BRANCH_CONFIGS}


def browser_config_records() -> list[dict[str, str]]:
    """Return the supported-branch fields consumed by the static browser app."""

    return [
        {
            "branch": config.branch,
            "site": config.site,
            "label": config.label,
            "jp_branch_tag": config.jp_branch_tag,
        }
        for config in SUPPORTED_BRANCH_CONFIGS
    ]


def render_browser_config() -> str:
    """Render the committed JavaScript artifact loaded before the browser app."""

    records = json.dumps(browser_config_records(), ensure_ascii=False, indent=2)
    return (
        '"use strict";\n\n'
        "// Generated by python -m scripts.commands.build_browser_config. Do not edit manually.\n"
        "globalThis.SCP_TAG_TRANSLATION_BRANCHES = Object.freeze(\n"
        f"{indent(records, '  ')}.map(Object.freeze),\n"
        ");\n"
    )

def source_site_for_branch(branch: str) -> str:
    try:
        return BRANCH_CONFIG_BY_CODE[branch].site
    except KeyError as exc:
        raise ValueError(f"unsupported corpus branch: {branch}") from exc


def jp_branch_tag_for_branch(branch: str) -> str:
    try:
        return BRANCH_CONFIG_BY_CODE[branch].jp_branch_tag
    except KeyError as exc:
        raise ValueError(f"unsupported corpus branch: {branch}") from exc
