"""Render and publish browser branch configuration."""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import indent
from typing import TypedDict

from scripts.domain.branch_config import SUPPORTED_BRANCH_CONFIGS
from scripts.infrastructure.atomic_output import publish_files_atomically
from scripts.infrastructure.data_paths import BROWSER_CONFIG_PATH
from scripts.infrastructure.json_io import write_staged_text

DEFAULT_OUTPUT = BROWSER_CONFIG_PATH


class BrowserBranchRecord(TypedDict):
    branch: str
    site: str
    label: str
    jp_branch_tag: str


def browser_config_records() -> list[BrowserBranchRecord]:
    """Return the browser-specific projection of the branch registry."""

    return [
        {
            "branch": config.branch,
            "site": config.site,
            "label": config.label,
            "jp_branch_tag": config.jp_branch_tag,
        }
        for config in SUPPORTED_BRANCH_CONFIGS
    ]


def render_browser_config() -> str:
    """Render the JavaScript artifact consumed by the static browser app."""
    records = json.dumps(browser_config_records(), ensure_ascii=False, indent=2)
    return (
        '"use strict";\n\n'
        "// Generated by python -m scripts.commands.build_browser_config. Do not edit manually.\n"
        "globalThis.SCP_TAG_TRANSLATION_BRANCHES = Object.freeze(\n"
        f"{indent(records, '  ')}.map(Object.freeze),\n"
        ");\n"
    )


def publish_browser_config(
    output: Path | None = None,
) -> None:
    """Render and atomically publish the browser configuration artifact.

    Raises:
        OSError: If staging, replacement, rollback, or cleanup cannot access
            the configured output path.
    """
    content = render_browser_config()
    publish_files_atomically({
        output or DEFAULT_OUTPUT: lambda temporary: write_staged_text(temporary, content),
    })


__all__ = [
    "DEFAULT_OUTPUT",
    "BrowserBranchRecord",
    "browser_config_records",
    "publish_browser_config",
    "render_browser_config",
]
