"""Render and publish browser branch configuration."""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import indent

from scripts.domain.branch_config import browser_config_records
from scripts.infrastructure.atomic_output import publish_files_atomically
from scripts.infrastructure.data_paths import BROWSER_CONFIG_PATH
from scripts.infrastructure.json_io import write_text

DEFAULT_OUTPUT = BROWSER_CONFIG_PATH


def render_browser_config() -> str:
    """Render the JavaScript artifact consumed by the static browser app."""
    records = json.dumps(browser_config_records(), ensure_ascii=False, indent=2)
    return (
        '"use strict";\n\n'
        "// Generated by python -m scripts.commands.build_browser_config. Do not edit manually.\n"
        "globalThis.SCP_TAG_TRANSLATION_BRANCHES = Object.freeze(\n"
        f"{indent(records, '  ')}.map(Object.freeze),\n"
        ");\n"
    )


def publish_browser_config(
    output: Path = DEFAULT_OUTPUT,
    *,
    publish=publish_files_atomically,
) -> None:
    """Render and atomically publish the browser configuration artifact."""
    content = render_browser_config()
    publish({
        output: lambda temporary: write_text(temporary, content),
    })


__all__ = ["DEFAULT_OUTPUT", "publish_browser_config", "render_browser_config"]
