"""Publish browser branch metadata rendered by the domain configuration."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from textwrap import indent

from scripts.infrastructure.atomic_output import publish_files_atomically
from scripts.infrastructure.data_paths import BROWSER_CONFIG_PATH
from scripts.domain.branch_config import browser_config_records
from scripts.infrastructure.json_io import write_text

DEFAULT_OUTPUT = BROWSER_CONFIG_PATH

def render_browser_config() -> str:
    """Render the JavaScript artifact consumed by the static browser app."""
    records = json.dumps(browser_config_records(), ensure_ascii=False, indent=2)
    return (
        '"use strict";\n\n'
        "// Generated by python -m scripts.commands.build_browser_config. Do not edit manually.\n"
        "globalThis.SCP_TAG_TRANSLATION_BRANCHES = Object.freeze(\n"
        f"{indent(records, '  ')}.map(Object.freeze),\n"
        ");\n"
    )


def publish_browser_config(output: Path = DEFAULT_OUTPUT) -> None:
    content = render_browser_config()
    publish_files_atomically(
        {
            output: lambda temporary: write_text(temporary, content),
        }
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="ブラウザ用の支部設定JavaScriptを生成する",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"出力先（デフォルト: {DEFAULT_OUTPUT}）",
    )
    args = parser.parse_args()

    try:
        publish_browser_config(args.output)
    except (OSError, ValueError) as error:
        print(f"エラー: ブラウザ設定の生成に失敗しました: {error}")
        sys.exit(1)
    print(f"browser config: {args.output}")


if __name__ == "__main__":
    main()
